package com.example.dao;

import com.example.dao.entity.Words;
import com.example.dao.entity.WordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    long countByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int deleteByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int insert(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int insertSelective(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    List<Words> selectByExample(WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    Words selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Words record, @Param("example") WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Words record, @Param("example") WordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Words record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Words record);
}