package com.example.dao.entity;

public class Words {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.word
     *
     * @mbg.generated
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words.japanese
     *
     * @mbg.generated
     */
    private String japanese;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.id
     *
     * @return the value of words.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.id
     *
     * @param id the value for words.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.word
     *
     * @return the value of words.word
     *
     * @mbg.generated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.word
     *
     * @param word the value for words.word
     *
     * @mbg.generated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words.japanese
     *
     * @return the value of words.japanese
     *
     * @mbg.generated
     */
    public String getJapanese() {
        return japanese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words.japanese
     *
     * @param japanese the value for words.japanese
     *
     * @mbg.generated
     */
    public void setJapanese(String japanese) {
        this.japanese = japanese == null ? null : japanese.trim();
    }
}